### ISSUE TITLE
Add port table

### ISSUE THREAD

**Issue by Gamatek** [p-dor/LiveboxMonitor#41]
It would be cool to have a new menu to manage ports and also static/dynamic ip!

**Comment by Gamatek** [comment]
Ha okay thank you, can't wait for the update!

**Comment by Gamatek** [comment]
Ha okay thank you, can't wait for the update!

**Comment by p-dor** [comment]
Ok closing.
And good idea for the Livebox API, I have a lot of internal references, result of hours of reverse engineering but not in form that can be published in an understandable way.
Actually I have a lot of docs to publish to really make this project Open Source: design documentation, coding rules, how to 
make builds with PyInstaller, etc... But I prefer for the moment spending my little time to implement evolutions, that's why...
