### ISSUE TITLE
liveboxmonitor displays a wrong list

### ISSUE THREAD

**Issue by pbranly** [p-dor/LiveboxMonitor#61]
Hi
Is it possible to reset the list of terminals ?
I use now an external router connected to the livebox without the livebox wifi.
Program should show only the connection of the TV decoder and the router while it always shows the historical status
![2024-04-04_15-17](https://github.com/p-dor/LiveboxMonitor/assets/22018509/9a6238b8-1c89-4e3d-b18d-640bd702417a)

Thanks
Phil

**Comment by p-dor** [comment]
Hi @pbranly, the program just displays what the Livebox "remembers".
When a device connects it remembers it for a while so that you can view the history (and it can help you to detect potentially unwanted connections, from unknow devices for examples).
In your case if you want to have the Livebox "forgetting" some devices quicker than the normal inactivity timeout (~1 month) you have to go to "Infos Appareil" tab, select each device you want to "forget" and click on the "Oublier..." button, it will make it...
